config/routes.rb
Noobninja::Application.routes.draw do
  authenticated :user do
    root to: 'lessons#index'
  end
  root to: 'users#welcome'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users
  resources :lessons
  resources :requests
  resources :offers
  resources :meetings
  resources :memberships
  resources :donations

  match 'book_meeting/:id' => 'meetings#book_meeting', as: :book_meeting
  match 'welcome' => 'users#welcome', as: :welcome

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :lesson
  has_many :meeting_users
  has_many :users, through: :meeting_users
  attr_accessible :adjourned, :booked, :capacity, :duration, :start_time

  validates :start_time, presence: true

  def start_time=(input)
    zone = self.lesson.user.time_zone
    write_attribute :start_time, input.class == DateTime ? input : ActiveSupport::TimeZone[zone].parse(input).utc
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_filter :set_meeting
  before_filter :user_subscribed?
  before_filter :show_booked_meeting?, only: [:show]
  before_filter :meeting_booked?, only: [:book_meeting]

  def show
  end

  def book_meeting
    @customer = @lesson.type == "Request" ? @lesson.user : current_user
    @description = params[:donate].present? || @lesson.donate == true ? "Donation - #{@lesson.donate == true ? @lesson.user.name : current_user.name} (#{@lesson.donate == true ? @lesson.user.email : current_user.email}) via #{@customer.name} (#{@customer.email}) for #{@lesson.type} #{@lesson.id}" : "#{@customer.name} (#{@customer.email}) for #{@lesson.type} #{@lesson.id}"

    if params[:free].present?
      current_user.increment!(:freebies)
    else
      begin
        @amount = @lesson.amount
        Stripe::Charge.create(
          amount: @amount,
          currency: "usd",
          customer: @customer.membership.stripe_customer_id,
          description: @description
        )
      rescue
        redirect_to @meeting, notice: "There was an error with #{@lesson.type == 'Request' ? 'the requester\'s' : 'your'} card. Please contact us at help@noobninja.com for assistance."
      end
    end


    if @lesson.donate == true
      @lesson.user.donations.create(charity: "charity: water", amount: @amount, lesson_id: @lesson.id, via_user_id: current_user.id, counted: true)
      current_user.donations.create(charity: "charity: water",amount: @amount, lesson_id: @lesson.id)
    elsif params[:donate].present?
      current_user.donations.create(charity: "charity: water",amount: @amount, lesson_id: @lesson.id, counted: true)
    end

    @lesson.update_attributes(booked: true) if @lesson.type == "Request"
    @meeting.update_attributes(booked: true)

    @meeting.users << current_user unless @meeting.users.include?(current_user)
    @meeting.users << @lesson.user unless @meeting.users.include?(@lesson.user)

    if @lesson.type == "Request"
      UserMailer.meeting_booked_email(@lesson.user, current_user, @meeting).deliver
      UserMailer.meeting_confirmation_email(current_user, @lesson.user, @meeting).deliver
    else
      UserMailer.meeting_booked_email(current_user, @lesson.user, @meeting).deliver
      UserMailer.meeting_confirmation_email(@lesson.user, current_user, @meeting).deliver
    end

    respond_to do |format|
      format.html { redirect_to @meeting, notice: 'Lesson successfully booked.' }
    end
  end

  private
  def set_meeting
    @meeting = Meeting.find(params[:id])
    @lesson = @meeting.lesson
  end

  def user_subscribed?
    if current_user.teacher? && @lesson.type != "Request"
      redirect_to edit_membership_path(current_user.membership), notice: "Help support NoobNinja by subscribing before requesting help."
    elsif !current_user.member? && @lesson.type != "Request" && @lesson.amount > 0
      redirect_to new_membership_path, notice: "Help support NoobNinja by subscribing before requesting help."
    end
  end

  def show_booked_meeting?
    if @lesson.booked? && !@meeting.users.include?(current_user)
      redirect_to lessons_path, notice: 'Unfortunately, this lesson has already been booked.'
    elsif @meeting.booked? && !@meeting.users.include?(current_user)
      redirect_to lessons_path, notice: 'Unfortunately, this meeting time has just been booked.'
    end
  end

  def meeting_booked?
    redirect_to lessons_path, notice: 'Unfortunately, this meeting time has just been booked.' if @meeting.booked?
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_meeting.html.slim
.meeting
  ' Meeting with
  - if meeting.lesson.user == current_user
    - meeting.users.uniq.delete_if{|x| x == current_user }.each do |user|
      .meeting-user
        = link_to user.name, user
        ' ( #{user.chat_email} )
    ' on
  - else
    .meeting-user
      = link_to meeting.lesson.user.name, meeting.lesson.user
      ' ( #{meeting.lesson.user.chat_email} )
    ' on
  strong #{meeting.start_time.strftime("%B %-d")}&nbsp;
  ' at
  strong #{meeting.start_time.strftime("%-l:%M %p")}&nbsp;
  ' for
  = link_to meeting.lesson.name, meeting.lesson

app/views/meetings/show.html.slim
.row
  .small-12.large-12.columns
    .section.top
      = render 'layouts/flash'
      = render partial: "lessons/lesson", object: @lesson, as: :lesson
      - if @meeting.lesson.description.present?
        .meeting-lesson-description style="border-top: 2px solid #DDD; background: whiteSmoke; border-radius: 0 0 4px 4px; color: #706C75; font-weight: 400; padding: 20px 40px"
          = @meeting.lesson.description
    .section
      - if @meeting.booked?
        .section-header
        .book-lesson
          .book-lesson-instructions
            h3 Instructions
            br
            ' You'll be meeting with #{@lesson.user.first_name} on
            br
            strong #{Time.zone.parse(@meeting.start_time.to_s).strftime("%B %-d")}&nbsp;
            ' at
            strong #{Time.zone.parse(@meeting.start_time.to_s).strftime("%-l:%M %p")}&nbsp;
            BR
            strong #{@lesson.user.first_name} (#{@lesson.user.chat_email})
            br
            | should send a Google+ Hangouts invite to
            br
            strong #{current_user.name} (#{current_user.chat_email})
            BR
            | The lesson is intended to be up to 10 minutes long, please be repectful of this time limit and give advance warning if you will be unable to attend.
        .section-footer
      - else
        .section-header
        .book-lesson
          - if @lesson.type == "Request"
            div
              ' I can help #{@lesson.user.first_name} learn about the topic specified above on
              br
              strong #{Time.zone.parse(@meeting.start_time.to_s).strftime("%B %-d")}&nbsp;
              ' at
              strong #{Time.zone.parse(@meeting.start_time.to_s).strftime("%-l:%M %p")}&nbsp;
              - if @lesson.amount?
                ' for
                strong $#{@lesson.cost}
          - else
            div
              ' I want to learn about the topic specified above from #{@lesson.user.first_name} on
              br
              strong #{Time.zone.parse(@meeting.start_time.to_s).strftime("%B %-d")}&nbsp;
              ' at
              strong #{Time.zone.parse(@meeting.start_time.to_s).strftime("%-l:%M %p")}&nbsp;
              - if @lesson.amount?
                ' for
                strong $#{@lesson.cost}
          - if @lesson.amount == 0
            = link_to book_meeting_path(@meeting, free: true), class: "radius button expand" do
              | BOOK FREE LESSON
          - elsif @lesson.type == "Request"
            - if current_user.member?
              = link_to book_meeting_path(@meeting), class: "radius button expand" do
                | BOOK LESSON FOR $#{@lesson.cost}
              br
            - else
              .provide-details
                | You must #{link_to "provide your account details", new_membership_path(teacher: true)}
                br
                | to collect the $#{@lesson.cost} tip for this lesson
                br
            = link_to book_meeting_path(@meeting, free: true), class: "radius button expand" do
              | BOOK LESSON FOR FREE
            br
            = link_to book_meeting_path(@meeting, donate: true), class: "radius button expand" do
              | BOOK LESSON AND GIVE $#{@lesson.cost} TO CHARITY
          - else
            = link_to book_meeting_path(@meeting), class: "large radius button" do
              | BOOK LESSON FOR $#{@lesson.cost}
            - if @lesson.donate?
              div style="margin-top: 2em"
                i.icon-heart style="margin-right: 10px"
                | Proceeds from this lesson go towards our #{link_to "fundraising goal", donations_path}
        .section-footer
    = render 'layouts/footer'