config/routes.rb
Noobninja::Application.routes.draw do
  authenticated :user do
    root to: 'lessons#index'
  end
  root to: 'users#welcome'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users
  resources :lessons
  resources :requests
  resources :offers
  resources :meetings
  resources :memberships
  resources :donations

  match 'book_meeting/:id' => 'meetings#book_meeting', as: :book_meeting
  match 'welcome' => 'users#welcome', as: :welcome

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  acts_as_taggable

  belongs_to :user
  has_many :meetings, order: 'meetings.start_time'
  has_many :meeting_users, through: :meetings
  has_many :users, through: :meeting_users
  has_many :donations

  accepts_nested_attributes_for :meetings, allow_destroy: true

  attr_accessible :amount, :booked, :description, :name, :tag_list, :type, :meetings_attributes, :donate, :user_to_notify
  attr_accessor :user_to_notify

  validates :name, presence: true
  validates :amount, presence: true
  validate :number_of_tags

  scope :with_available_meetings, -> { includes(:user, :meetings).where("meetings.booked = ? AND meetings.start_time >= ?", false, Time.zone.now).order("meetings.start_time") }

  def available_meetings
    meetings.where("meetings.start_time >= ?", Time.zone.now)
  end

  def cost
    amount / 100
  end

  def number_of_tags
    errors.add(:lesson, "- please add at least 1 tag") if self.tag_list.length < 1
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    if params[:type] && params[:tag]
      @lessons = params[:type].capitalize.constantize.where(booked: false).tagged_with(params[:tag]).with_available_meetings
    elsif params[:type]
      @lessons = params[:type].capitalize.constantize.where(booked: false).with_available_meetings
    elsif params[:tag]
      @lessons = Lesson.where(booked: false).tagged_with(params[:tag]).with_available_meetings
    else
      @lessons = Lesson.where(booked: false).with_available_meetings
    end

    if @lessons.blank?
      if params[:type] == "request"
        @inactive_lessons = nil
      elsif params[:tag]
        @inactive_lessons = Offer.includes(:user, :meetings).tagged_with(params[:tag])
      else
        @inactive_lessons = Offer.includes(:user, :meetings).all
      end
    else
      if params[:tag]
        @inactive_lessons = Offer.includes(:user, :meetings).where("lessons.id NOT IN (?)", @lessons.map(&:id)).tagged_with(params[:tag])
      else
        @inactive_lessons = Offer.includes(:user, :meetings).where("lessons.id NOT IN (?)", @lessons.map(&:id))
      end
    end

    @selected_tag = ActsAsTaggableOn::Tag.where(name: params[:tag]).first if params[:tag]
    if params[:type] == "request"
      @lesson_tags = @lessons.map(&:tags)
    else
      @lesson_tags = (@lessons + @inactive_lessons).map(&:tags)
    end
    @lesson_tags = @lesson_tags.flatten.uniq.sort { |x,y| x.name <=> y.name }
    @lesson_tags = @lesson_tags + [@selected_tag] if params[:tag]

    # @booked_lessons = Offer.includes(:user, :meetings).where("meetings.start_time >= ?", Time.zone.now).order("meetings.start_time")
    # @booked_lessons = Offer.includes(:user, :meetings).where("lessons.id NOT IN (?)", @lessons.map(&:id)).where("meetings.start_time >= ?", Time.zone.now).order("meetings.start_time")
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_empty.html.slim
.empty-lessons
  | There aren't any #{params[:type].present? ? params[:type].pluralize : 'lessons'} that match this criteria at the moment.
  - if params[:type].blank? && params[:type].blank?
    = link_to new_request_path do
      i.icon-plus style="margin-right: 8px"
      | Request Lesson
    = link_to new_offer_path do
      i.icon-plus style="margin-right: 8px"
      | Offer Lesson
  - else
    = link_to "Clear Filters", lessons_path

app/views/lessons/_lesson.html.slim
.lesson.group class=("offer" if lesson.type == "Offer")
  .lesson-image
    = link_to image_tag(lesson.user.image_url(:thumb)), lesson.user
  - if lesson.amount?
    .lesson-amount
      - if lesson.donate?
        i.icon-heart
      span $
      = lesson.cost
  .lesson-content
    .lesson-title
      = link_to lesson.user.first_name, lesson.user
      span= lesson.type == "Offer" ? lesson.available_meetings.blank? ? "can teach" : "is teaching" : "wants to learn"
      .lesson-name= link_to lesson.name, lesson.meetings.first
    .lesson-meetings
      - lesson.available_meetings.each do |meeting|
        .lesson-meeting class=("#{'active' if current_page?(meeting_path(meeting))} #{'booked' if meeting.booked? && !meeting.users.include?(current_user)} #{'booked_by_me' if meeting.booked? && meeting.users.include?(current_user)}")
          = link_to meeting do
            i.icon-time
            = meeting.start_time.in_time_zone.strftime("%B %-d")
            span |
            = meeting.start_time.in_time_zone.strftime("%-l:%M %p")
      - if lesson.type == "Offer" && (current_user != lesson.user)
        .lesson-meeting
          = link_to new_request_path(lesson: lesson) do
            i.icon-time
            | Request Lesson
      - if current_user == lesson.user
        .lesson-meeting
          = link_to lesson.type == "Offer" ? edit_offer_path(lesson) : edit_request_path(lesson) do
            i.icon-edit
            | Edit

app/views/lessons/index.html.slim
- content_for :javascript do
  = javascript_include_tag "lessons"
.row
  .small-12.large-12.columns
    .section.top.lessons-index
      = render 'layouts/flash'
      .lessons-bar
        .row
          .large-9.columns
            ul
              li.create
                = link_to new_lesson_path do
                  i.icon-plus
                  | NEW
              li.learn class=("active" if params[:type] == "offer")
                = link_to "LESSONS", params[:type] == "offer" ? lessons_path(tag: params[:tag]) : lessons_path(type: "offer", tag: params[:tag])
              li.teach class=("active" if params[:type] == "request")
                = link_to "REQUESTS", params[:type] == "request" ? lessons_path(tag: params[:tag]) : lessons_path(type: "request", tag: params[:tag])
              - if params[:type].present? || params[:tag].present?
                .clear-filters= link_to "Clear Filters", lessons_path
          .large-3.columns
            ul
              = collection_select :lesson, :tags, @lesson_tags, :slug, :name, {include_blank: true, selected: @selected_tag.try(:slug)}, {class: "select2-select"}
    .section
      - if @lessons.blank? && @inactive_lessons.blank?
        = render "lessons/empty"
      - else
        = render partial: "lessons/lesson", collection: @lessons, as: :lesson
        - unless params[:type] == "request"
          = render partial: "lessons/lesson", collection: @inactive_lessons, as: :lesson
    = render 'layouts/footer'

app/views/lessons/new.html.slim
.row
  .small-12.large-6.columns.small-centered.large-centered
    .section.top
      #new_lesson
        = link_to new_request_path, class: "large radius button expand" do
          | REQUEST LESSON
        = link_to new_offer_path, class: "large secondary radius button expand" do
          | OFFER LESSON
    = render 'layouts/footer'