config/routes.rb
Noobninja::Application.routes.draw do
  authenticated :user do
    root to: 'lessons#index'
  end
  root to: 'users#welcome'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users
  resources :lessons
  resources :requests
  resources :offers
  resources :meetings
  resources :memberships
  resources :donations

  match 'book_meeting/:id' => 'meetings#book_meeting', as: :book_meeting
  match 'welcome' => 'users#welcome', as: :welcome

end

app/views/layouts/_analytics.html.slim
javascript:
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-7365777-10']);
  _gaq.push(['_setDomainName', 'noobninja.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/layouts/_flash.html.slim
- if notice || alert
  .alert-box.secondary data-alert=""
    = notice || alert
    a.close href="#"

app/views/layouts/_footer.html.slim
footer
  .row
    .small-12.large-12.columns
      .footer
        - mail_content = capture do
          i.icon-envelope
        = mail_to "sensei@noobninja.com", mail_content, encode: "hex", target: "_blank"
        = link_to "https://twitter.com/noobninjas", target: "_blank" do
          i.icon-twitter
        div NoobNinja © 2013

app/views/layouts/_navigation.html.slim
.contain-to-grid
  nav.top-bar
    ul.title-area
      li.name
        h1= link_to root_path do
          | noob
          span ninja
      li.toggle-topbar.menu-icon
        = link_to '#' do
          span
    section.top-bar-section
      ul.right
        - if user_signed_in?
          li class=("active" if current_page?(root_path) || current_page?(lessons_path))
            = link_to root_path do
              span 道場
              | Dojo
          li class=("active" if current_page?(user_path(current_user)))
            = link_to current_user do
              span 前板
              | Dashboard
          li.has-dropdown
            a href="#"
              i.icon-cog style="margin: 0;"
            ul.dropdown
              li
                = link_to current_user.member? ? edit_membership_path(current_user.membership) : new_membership_path do
                  i.icon-credit-card
                  | Subscription
              li.divider
              li
                = link_to edit_user_registration_path do
                  i.icon-user
                  | Profile
              li.divider
              li
                = link_to destroy_user_session_path, method: :delete do
                  i.icon-signout
                  | Logout
        - else
          li= link_to 'ログイン Member Login', new_user_session_path

app/views/layouts/_twitter.html.slim
a href="https://twitter.com/share" class="twitter-share-button" data-url="http://noobninja.com/" data-text="NoobNinja - get and give 10-minute lessons on programming and design concepts for charity (and profit)" data-via="noobninjas" data-size="large" data-related="noobninjas"
  | Tweet
javascript:
  !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');

app/views/layouts/application.html.slim
doctype html
== "<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->"
== "<!--[if lt IE 7 ]> <html class=\"ie6\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 7 ]>    <html class=\"ie7\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 8 ]>    <html class=\"ie8\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 9 ]>    <html class=\"ie9\" lang=\"en\"> <![endif]-->"
== "<!--[if (gt IE 9)|!(IE)]><!--> <html lang=\"en\"> <!--<![endif]-->"
head
  meta charset="utf-8"
  meta http-equiv="X-UA-Compatible" content="IE=7"
  meta name="viewport" content="width=device-width, initial-scale=1.0"
  title= content_for?(:title) ? yield(:title) : "noob | ninja"
  = stylesheet_link_tag "application", media: "all"
  = javascript_include_tag "//use.typekit.com/ier1ulg.js", "vendor/custom.modernizr"
  = javascript_tag "try{Typekit.load()}catch(e){}"
  == yield :stripe
  = csrf_meta_tags
body
  = render 'layouts/navigation'
  == yield
  = javascript_include_tag "application"
  == yield :javascript
  = render 'layouts/analytics'
  = debug(params) if Rails.env.development?